# Site settings
title: Cara M. Antonaccio
description: 'Research Portfolio'
url: 'http://caraantonacc.io'
baseurl: ''
profilepic: '/images/cara.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Cara M. Antonaccio'
  email: antonaca@bc.edu
  twitter_username: caraantonaccio
  scholar_username:  citations?user=zYG1Op8AAAAJ&hl=en
#  facebook_username: joshgerdes
  github_username:  antonaca
  linkedin_username:  cara-antonaccio-62595554

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
